# -*- coding: utf-8 -*-
"""Provider management — models, presets, persistent store, key rotation."""

from .models import (
    ActiveModelsInfo,
    KeyEntry,
    KeyHealth,
    KeyInfoMasked,
    ModelInfo,
    ModelSlotConfig,
    ProviderConfig,
    ProviderDefinition,
    ProviderHealthResult,
    ProviderInfo,
    ProviderSettings,
    ProvidersData,
    ResolvedModelConfig,
    RotationStrategy,
)
from .registry import (
    PROVIDER_PRESETS,
    PROVIDERS,
    get_preset,
    get_provider,
    list_presets,
    list_providers,
)
from .store import (
    add_key,
    batch_add_keys,
    create_provider,
    delete_provider,
    get_active_llm_config,
    load_providers_json,
    mask_api_key,
    remove_key,
    report_key_failure,
    report_key_success,
    save_providers_json,
    set_active_llm,
    toggle_key,
    update_provider,
    update_provider_settings,
)

__all__ = [
    # models
    "ActiveModelsInfo",
    "KeyEntry",
    "KeyHealth",
    "KeyInfoMasked",
    "ModelInfo",
    "ModelSlotConfig",
    "ProviderConfig",
    "ProviderDefinition",
    "ProviderHealthResult",
    "ProviderInfo",
    "ProviderSettings",
    "ProvidersData",
    "ResolvedModelConfig",
    "RotationStrategy",
    # presets
    "PROVIDER_PRESETS",
    "PROVIDERS",
    "get_preset",
    "get_provider",
    "list_presets",
    "list_providers",
    # store
    "add_key",
    "batch_add_keys",
    "create_provider",
    "delete_provider",
    "get_active_llm_config",
    "load_providers_json",
    "mask_api_key",
    "remove_key",
    "report_key_failure",
    "report_key_success",
    "save_providers_json",
    "set_active_llm",
    "toggle_key",
    "update_provider",
    "update_provider_settings",
]
